class ProviderError(Exception):
    ...

class TimeoutError(ProviderError):
    ...

class RateLimitError(ProviderError):
    ...

class ApiError(ProviderError):
    ...

class AuthError(ProviderError):
    ...
